development: &default
  adapter: postgresql
  database: dummy_development
  encoding: unicode
  pool: 5
  <% if ENV.fetch("GITHUB_ACTIONS", false) || ENV.fetch("CODESPACES", false) %>
  host: localhost
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  <% end %>

test:
  primary:
    <<: *default
    database: dummy_test
  secondary:
    <<: *default
    database: dummy_test
    replica: true
